### ISSUE TITLE
Doesn't work at all now

### ISSUE THREAD

**Issue by Rudd-O** [limengdu/MR60BHA2_ESPHome_external_components#12]
I have compiled a firmware using this component as external:

```
external_components:
  - source: github://limengdu/MR60BHA2_ESPHome_external_components
    components: [seeed_mr60bha2]


uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Target detected"

sensor:
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    distance:
      name: "Distance to detection object"
```

Now none of the MR60BHA2 sensors work (they used to work although the device crashed a lot).

They all say Unknown in Home Assistant.

All other non MR60BHA2 sensors work correctly.

What happened?

**Comment by Rudd-O** [comment]
```
`[11:04:04][E][seeed_mr60bha2:115]: DATA_CKSUM_FRAME ERROR: 0x48
```

Sometimes.

**Comment by Rudd-O** [comment]
If I disable the distance to detection object sensor, suddenly the breath and heart rate sensors begin working.

**Comment by ragharamani** [comment]
I'm having the same issue,  the luminance sensor works but nothing else does. even when I disable "Distance to detection object"

`i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Information"

sensor:
  - platform: bh1750
    name: "Seeed MR60BHA2 Illuminance"
    address: 0x23
    update_interval: 1s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    #distance:
      #name: "Distance to detection object"
    num_targets:
      name: "Target Number"
`

**Comment by dsoiM** [comment]
> I'm having the same issue, the luminance sensor works but nothing else does. even when I disable "Distance to detection object"
> 
> ```
> i2c:
>   sda: GPIO22
>   scl: GPIO23
>   scan: true
>   id: bus_a
> 
> uart:
>   id: uart_bus
>   baud_rate: 115200
>   rx_pin: 17
>   tx_pin: 16
>   parity: NONE
>   stop_bits: 1
> 
> seeed_mr60bha2:
>   id: my_seeed_mr60bha2
> 
> binary_sensor:
>   - platform: seeed_mr60bha2
>     has_target:
>       name: "Person Information"
> 
> sensor:
>   - platform: bh1750
>     name: "Seeed MR60BHA2 Illuminance"
>     address: 0x23
>     update_interval: 1s
>   - platform: seeed_mr60bha2
>     breath_rate:
>       name: "Real-time respiratory rate"
>     heart_rate:
>       name: "Real-time heart rate"
>     #distance:
>       #name: "Distance to detection object"
>     num_targets:
>       name: "Target Number"
> ```

Same issue here. I used the prebuilt firmware from https://limengdu.github.io/MR60BHA2_ESPHome_external_components/

**Comment by koszta** [comment]
It's likely due to some recent changes. I reverted all the commits that were blocking sensor data to be directly sent to HA to see what is actually received from the radar module. Now it seems like it's sending sensor data. It's still not super stable using the radar firmware version 1.6.4, I'll try later to flash 1.6.5.

https://github.com/koszta/MR60BHA2_ESPHome_external_components/tree/restore-publishing-all-states

You can try it by replacing the git url:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/koszta/MR60BHA2_ESPHome_external_components
      ref: restore-publishing-all-states
    components: [ seeed_mr60bha2 ]
    refresh: 0s
```

Not sending all the data from the sensor is discouraged, see the comments of an ESPHome developer:
https://github.com/esphome/esphome/pull/8209#issuecomment-2646731542

**Comment by koszta** [comment]
If you don't want to send duplicate updates, you can use the ESPHome filters for example

```yaml
  distance:
      name: "Distance to detection object"
      filters:
        - delta: 0.01
```

**Comment by koszta** [comment]
With the help of the reset pin (GPIO21) you can reset the stuck radar module, so you don't need to power cycle it, you can do it remotely. It should be possible to trigger this on certain conditions or periodically.

```yaml
output:
  - platform: gpio
    pin: GPIO21
    inverted: True
    id: reset

button:
  - platform: output
    name: "Reset radar"
    output: reset
    duration: 50ms
```
